-- auto Generated on 2020-04-30
-- DROP TABLE IF EXISTS display_plan;
CREATE TABLE display_plan(
	plan_id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	movie_id INT (11) NOT NULL DEFAULT -1 COMMENT '对应电影id',
	start_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '开始时间',
	end_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '结束时间',
	play_time DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '反映的日期',
	hall_place VARCHAR (50) NOT NULL DEFAULT '' COMMENT '几号展映厅',
	hall_type VARCHAR (50) NOT NULL DEFAULT '' COMMENT '展映厅类型 3d 2d',
	plan_status INT (11) NOT NULL DEFAULT -1 COMMENT '放映状态 0未放映 1已放映 2取消',
	movie_price DOUBLE (16,4) NOT NULL DEFAULT -1.0 COMMENT '电影价格',
	movie_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '电影名',
	PRIMARY KEY (plan_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'display_plan';
