-- auto Generated on 2020-04-26
-- DROP TABLE IF EXISTS movie;
CREATE TABLE movie(
	movie_id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'movie_id',
	movie_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '名称',
	movie_introduce VARCHAR (50) NOT NULL DEFAULT '' COMMENT '简介',
	movie_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '上映时间',
	movie_type INT (11) NOT NULL DEFAULT -1 COMMENT '体裁',
	movie_price DOUBLE (16,4) NOT NULL DEFAULT -1.0 COMMENT '价格',
	movie_stars INT (11) NOT NULL DEFAULT -1 COMMENT '电影评分',
	movie_src VARCHAR (50) NOT NULL DEFAULT '' COMMENT '电影海报',
	movie_showtime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '放映时间',
	movie_status INT (11) NOT NULL DEFAULT -1 COMMENT '电影状态',
	PRIMARY KEY (movie_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'movie';
