-- auto Generated on 2020-05-06
-- DROP TABLE IF EXISTS orders;
CREATE TABLE orders(
	id INT (11) NOT NULL AUTO_INCREMENT COMMENT 'id',
	order_id VARCHAR (50) NOT NULL DEFAULT '' COMMENT 'UUID',
	order_product VARCHAR (50) NOT NULL DEFAULT '' COMMENT '订单物品 一大串',
	order_number VARCHAR (50) NOT NULL DEFAULT '' COMMENT '订单数量 总共有几个物品',
	order_price DOUBLE (16,4) NOT NULL DEFAULT -1.0 COMMENT '订单总价',
	order_status INT (11) NOT NULL DEFAULT -1 COMMENT '订单状态 0待支付 1已支付 2等待处理 3取消 4关闭 5完成',
	movie_name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '电影名',
	create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
	hall_type VARCHAR (50) NOT NULL DEFAULT '' COMMENT '2D 3D厅',
	user_id INT (11) NOT NULL DEFAULT -1 COMMENT 'user_id',
	create_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建日期',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'orders';
